### ISSUE TITLE
xcode8的问题

### ISSUE THREAD

**Issue by moyunmo** [KOmyself/WXFastlaneJenkins#1]
您好， 

在xcode8下，更换bundleId同时更改profilevisioning描述文件打企业包的时候，你的fastfile里的lane命令有效么？  我fastfile和你差不多，在xcode7是OK的，xcode8好像不行，不知道你有没遇到过, 详细情况是在xcode中看到描述文件和bundleId确实是改过来了， 但是描述文件错误提示里 还是针对于在bundleId改之前的bundleId

**Comment by KOmyself** [comment]
你好，刚注意到消息，xcode8下，只通过update_provisioning_file修改是无效的，还需要修改provisioning_file_specifier(我在实际中只修改这一个就可以)，fastlane没有这样的action，但是有一个plugin，upate_provisioning_profile_specifier你可以安装一个这个插件

**Comment by moyunmo** [comment]
嗯，谢谢！
我最后直接用Ruby写了一个脚本，去更改xcode的所有工程配置， 最后也都解决了，谢谢，里面确实直接修改工程的provisioning_profile_specifier就可以了
